First pass at Any().such_that()
man-group/mockextras pull request #11
Opened 2017-10-20 03:55 UTC by Jdsleppy

PR to address issue #10 .

From that issue:
I would like to use `mockextras` in all my testing, but first I would like to add a couple of features I see as very generic and useful to everyone, if you agree.  The first on my wishlist is the ability to specify arbitrary predicates to an `Any` matcher.

```python
loud_short_string = (
    Any(str)
    .such_that(lambda s: len(s) < 6)
    .such_that(lambda s: s.upper() == s)
)
assert loud_short_string == "HEY"

positive_int = Any(int).such_that(lambda x: x > 0)
assert positive_int != -2
```

My solution is tested and I think it fits in with the rest of the fluent interface.  I'm happy to battle-harden it in the real world for a time, too, since I _just_ finished the feature.

2017-10-20 11:55 UTC, burrowsa requested changes
Looks good, just a few tweaks required

2017-10-20 11:55 UTC, burrowsa commented on test/test_matchers.py
> +def test_any_such_that_equality():
Please split this up into individual tests, the problem with long tests such as this with lots of asserts is that if the first assert fails the rest are not run so you don't really know how bad the situation is -maybe you broke 1 test maybe you broke 50.

The fact that your asserts are grouped into symmetric pairs suggests that maybe a parameterized test might suit them

2017-10-20 11:55 UTC, burrowsa commented on mockextras/_matchers.py
> +        new_predicates.append(predicate)
```new_predicates = self._predicates + [predicate]``` should achieve the same thing in less lines

2017-10-20 14:02 UTC, Jdsleppy commented
Good points, I made those changes.  Let me know if there's anything else you see, or have thoughts on that parametrized test.

2017-10-21 09:25 UTC, burrowsa approved these changes
Looks god

2017-10-21 09:25 UTC, merged